### ISSUE TITLE
openocd  连不上

### ISSUE THREAD

**Issue by franktaTian** [jiegec/rocket-chip-vcu128#1]
Hi，
   感谢分享！我重新跑了一遍你的流程。但openocd  连不上。有什么要注意的地方吗？谢谢！

**Comment by jiegec** [comment]
时钟，复位，引脚绑定。

**Comment by jiegec** [comment]
还要注意一下 OpenOCD 的配置。

**Comment by franktaTian** [comment]
需要装什么驱动吗？我的是Ubuntu 20.04

**Comment by franktaTian** [comment]
还有，用Xilinx 以太网控制器时，需要License，我现在只能先去掉了。

**Comment by jiegec** [comment]
最近仓库更新了不少东西，如果还有兴趣的话，可以再尝试一下。如果 openocd 还是有问题，再 re-open。
